name: Diabetico

options:
  bundleIdPrefix: com.diabeteshealth
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "3B4BSY53LG"              # fill in your Apple Team ID

targets:
  Diabetico:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    sources:
      - path: Sources
        createIntermediateGroups: true

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.diabeto.app
        INFOPLIST_FILE: DiabetesHealth/Info.plist
        CODE_SIGN_ENTITLEMENTS: DiabetesHealth/DiabetesHealth.entitlements
        TARGETED_DEVICE_FAMILY: "1"   # 1 = iPhone, "1,2" = iPhone + iPad

    dependencies:
      - sdk: HealthKit.framework

    entitlements:
      path: DiabetesHealth/DiabetesHealth.entitlements
      properties:
        com.apple.developer.healthkit: true

    info:
      path: DiabetesHealth/Info.plist
      properties:
        CFBundleDisplayName: Diabetico
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSHealthShareUsageDescription: "Diabetico reads your glucose, sleep, and exercise data to generate personalised health insights."
        NSHealthUpdateUsageDescription: "Diabetico does not write any data to HealthKit."
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        ITSAppUsesNonExemptEncryption: false
